// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efrrfnnwnhtpajrdhduk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcnJmbm53bmh0cGFqcmRoZHVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjA1MTYsImV4cCI6MjA2NDgzNjUxNn0.bijmyp8P--lv5AbWNg5dPKSNAdls8w7etOJ29FA50xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);